swagger: '2.0'
info:
  description: Invoice chaincode for penalty scenario
  version: '1.0'
  title: Invoice API's
consumes:
  - application/x-www-form-urlencoded
produces:
  - application/json
parameters:
  materialNumber:
    name: materialNumber
    in: formData
    description: Part/Material Number
    required: true
    type: string
    maxLength: 64
  purchaseOrderNumber:
    name: purchaseOrderNumber
    in: formData
    description: Purchase Order Number
    required: true
    type: string
    maxLength: 64
  invoiceAmount:
    name: invoiceAmount
    in: formData
    description: Invoice Amount
    required: true
    type: string
    maxLength: 64
  expectedDate:
    name: expectedDate
    in: formData
    description: Expected Delivery Date
    required: false
    type: string
    maxLength: 64
  actualDate:
    name: actualDate
    in: formData
    description: Actual Delivery Date
    required: false
    type: string
    maxLength: 64
paths:
  '/invoiceForPenalty':
    post:
      operationId: createInvoice
      summary: Create Invoice
      parameters:
        - $ref: '#/parameters/materialNumber'
        - $ref: '#/parameters/purchaseOrderNumber'
        - $ref: '#/parameters/invoiceAmount'
      responses:
        '201':
          description: Invoice Created Successfully
        '406':
          description: Invalid Parameters
        '409':
          description: Invoice already exists
        '500':
          description: Internal Server Error
  '/invoiceForPenalty/getInvoiceAmountById':
    post:
      operationId: getInvoiceAmountById
      summary: Get Invoice Amount
      parameters:
        - $ref: '#/parameters/purchaseOrderNumber'
        - $ref: '#/parameters/materialNumber'
        - $ref: '#/parameters/expectedDate'
        - $ref: '#/parameters/actualDate'
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              text:
                type: string
        '404':
          description: Not Found